[open-ai]
VITE_OPEN_AI_API_KEY=''

[pusher.client]
VITE_PUSHER_CLUSTER=''
VITE_PUSHER_APP_KEY=''

[pusher.server]
VITE_PUSHER_APP_ID=''
VITE_PUSHER_SECRET=''

[supabase]
VITE_SUPABASE_DOMAIN=''
VITE_SUPABASE_TOKEN=''